### ISSUE TITLE
Null Checking

### ISSUE THREAD

**Issue by TrevorByram** [J8cob1/dash#61]
Check for Null return from API calls. If an API is called and returns Null we currently aren't checking for that. This will crash the entire app and make it impossible to use the app until the API call returns non-null. Which could take a while depending on why the API is returning Null (i.e. out of uses for the day.)

**Comment by heykc** [comment]
Hey Trevor, I could work on this if this still needs to be done ✌

**Comment by TrevorByram** [comment]
Thank you! This does still need to be done. We'd appreciate the help!

**Comment by heykc** [comment]
So I'm working on these changes and i noticed you were spreading all of this.state for every setState call. Is there a reason for this? If you really needed to spread the other state properties, these set states should be given a function rather than just an object, to ensure it's grabbing the most current state properties when it runs. 

Also, which APIs are responding with null values? all the APIs I can find on this project return a 400 or 403 if not a 200. I've refactored to account for the 4** responses now, but have not found an instance where we're getting null back. Any chance I could get a little more clarification on what you'd like to be checking for? Thanks!

**Comment by TrevorByram** [comment]
For the setState calls myself and the team were still learning React so I'm not entirely sure. As for the API's I think what you are doing should work perfectly! I think I misstated that the API would return null. Rather I think it was a function that called an API that returned null.
